/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Freepoly.org (https://sketchfab.com/blackrray)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-computer-02-freepolyorg-e55d089d02b5423b99c94ed56450aaa8
title: Old Computer 02-Freepoly.org
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
  }
  materials: {
    ['06___Default']: THREE.MeshStandardMaterial
    ['03___Default']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/computer.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials['06___Default']} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials['06___Default']} />
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials['06___Default']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials['03___Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer.glb')
